package org.janark.app.ui.theme

enum class ThemeId(
    val id: String,
    val label: String,
    val description: String,
    val swatches: Triple<Long, Long, Long>,
    val dark: Boolean,
) {
    BrandDay(
        "brand-day",
        "Brand Day",
        "White surfaces, deep navy type, orange actions — official Janark light.",
        Triple(0xFFFFFFFF, 0xFF002E57, 0xFFF89E17),
        dark = false,
    ),
    BrandWarm(
        "brand-warm",
        "Brand Warm",
        "Light yellow paper wash with the same navy and orange brand marks.",
        Triple(0xFFFFE7A3, 0xFF02274B, 0xFFF89E17),
        dark = false,
    ),
    BrandNight(
        "brand-night",
        "Brand Night",
        "Deep navy canvas, white type, golden accents — brand colors after dark.",
        Triple(0xFF02274B, 0xFFFFFFFF, 0xFFFFC83D),
        dark = true,
    ),
    Monsoon(
        "monsoon",
        "Monsoon",
        "Teal civic mist — water-and-sky palette for long reading sessions.",
        Triple(0xFFE8F1F2, 0xFF0B3D4A, 0xFF2A9D8F),
        dark = false,
    ),
    EmberGraphite(
        "ember-graphite",
        "Ember Graphite",
        "Charcoal surfaces with ember actions — focused night mode without brand navy.",
        Triple(0xFF1C1917, 0xFFFAFAF9, 0xFFEA580C),
        dark = true,
    ),
    ;

    companion object {
        fun from(raw: String?): ThemeId =
            entries.firstOrNull { it.id == raw } ?: BrandDay
    }
}

data class JanarkColors(
    val background: Long,
    val foreground: Long,
    val navy: Long,
    val navyMid: Long,
    val chrome: Long,
    val chromeMid: Long,
    val amber: Long,
    val amberBright: Long,
    val sand: Long,
    val cream: Long,
    val muted: Long,
    val line: Long,
    val surface: Long,
    val onChrome: Long,
    val success: Long,
    val danger: Long,
    val fact: Long,
    val news: Long,
)

fun colorsFor(theme: ThemeId): JanarkColors = when (theme) {
    ThemeId.BrandDay -> JanarkColors(
        background = 0xFFFFFFFF,
        foreground = 0xFF02274B,
        navy = 0xFF02274B,
        navyMid = 0xFF002E57,
        chrome = 0xFF02274B,
        chromeMid = 0xFF002E57,
        amber = 0xFFF89E17,
        amberBright = 0xFFFFC83D,
        sand = 0xFFFFE7A3,
        cream = 0xFFFFF8E8,
        muted = 0xFF5D6264,
        line = 0xFFD9DDE0,
        surface = 0xFFFFFFFF,
        onChrome = 0xFFFFF8E8,
        success = 0xFF1F6B4A,
        danger = 0xFF9B2C2C,
        fact = 0xFF002E57,
        news = 0xFF8A6A12,
    )
    ThemeId.BrandWarm -> JanarkColors(
        background = 0xFFFFE7A3,
        foreground = 0xFF02274B,
        navy = 0xFF02274B,
        navyMid = 0xFF002E57,
        chrome = 0xFF02274B,
        chromeMid = 0xFF002E57,
        amber = 0xFFF89E17,
        amberBright = 0xFFFFC83D,
        sand = 0xFFFFC83D,
        cream = 0xFFFFF4CC,
        muted = 0xFF5D6264,
        line = 0xFFE0C86A,
        surface = 0xFFFFF8E8,
        onChrome = 0xFFFFF8E8,
        success = 0xFF1F6B4A,
        danger = 0xFF9B2C2C,
        fact = 0xFF002E57,
        news = 0xFF8A6A12,
    )
    ThemeId.BrandNight -> JanarkColors(
        background = 0xFF02274B,
        foreground = 0xFFFFFFFF,
        navy = 0xFFFFFFFF,
        navyMid = 0xFFFFE7A3,
        chrome = 0xFF002E57,
        chromeMid = 0xFF0A3A66,
        amber = 0xFFFFC83D,
        amberBright = 0xFFF89E17,
        sand = 0xFF002E57,
        cream = 0xFF0A3058,
        muted = 0xFFA8B0B5,
        line = 0xFF5D6264,
        surface = 0xFF0A3A66,
        onChrome = 0xFFFFFFFF,
        success = 0xFF3DD68C,
        danger = 0xFFF87171,
        fact = 0xFFFFE7A3,
        news = 0xFFFFC83D,
    )
    ThemeId.Monsoon -> JanarkColors(
        background = 0xFFE8F1F2,
        foreground = 0xFF0B3D4A,
        navy = 0xFF0B3D4A,
        navyMid = 0xFF145566,
        chrome = 0xFF0B3D4A,
        chromeMid = 0xFF145566,
        amber = 0xFF2A9D8F,
        amberBright = 0xFF3DB8A8,
        sand = 0xFFD4E8EA,
        cream = 0xFFF3F9F9,
        muted = 0xFF5A7178,
        line = 0xFFB7CFD3,
        surface = 0xFFFFFFFF,
        onChrome = 0xFFF3F9F9,
        success = 0xFF1F6B4A,
        danger = 0xFF9B2C2C,
        fact = 0xFF145566,
        news = 0xFF8A6A12,
    )
    ThemeId.EmberGraphite -> JanarkColors(
        background = 0xFF1C1917,
        foreground = 0xFFFAFAF9,
        navy = 0xFFFAFAF9,
        navyMid = 0xFFE7E5E4,
        chrome = 0xFF292524,
        chromeMid = 0xFF44403C,
        amber = 0xFFEA580C,
        amberBright = 0xFFF97316,
        sand = 0xFF292524,
        cream = 0xFF1C1917,
        muted = 0xFFA8A29E,
        line = 0xFF44403C,
        surface = 0xFF292524,
        onChrome = 0xFFFAFAF9,
        success = 0xFF4ADE80,
        danger = 0xFFF87171,
        fact = 0xFFFED7AA,
        news = 0xFFFBBF24,
    )
}
